Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Philip Morris', 'André Calantzopoulos', 1973, 157.5 , 1)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Shell', 'Ben Van Beurden', 1996, 27, 1)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Ray Ban', 'Francesco Milleri', 2017, 10, 1)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Red Bull', 'Franz Watzlawick', 2005, 200, 0)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Aston Martin', 'Amedeo Felisa', 2018, 30, 0)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Honda', 'Takahiro Hachigo', 2019, 25, 0)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Petronas', 'Wan Zulkiflee Wan Ariffin', 2009, 125, 2)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Ineos', 'Sir James Arthur Ratcliffe', 2020, 35, 2)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('UBS', 'Ralph Hamers', 2010, 30, 2)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('BWT', 'Ralf Weber', 2022, 100, 3)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Castrol', 'Bernard Looney', 2022, 25, 3)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Microsoft', 'Satya Nadella', 1977, 30, 3)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Gulf', 'Michael K. Wirth', 1968, 145, 4)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Dell Technologies', 'Michael Dell', 2018, 50, 4)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Google', 'Sundar Pichai', 2022, 35, 4)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Haas', 'Gene Haas', 2016, 160, 7)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('MoneyGram', 'Alexander Holmes', 2022, 15, 7)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('IONOS', 'Achim Weiss', 2021, 15, 7)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Alfa Romeo', 'Jean-Philippe Imparato', 2018, 150, 5)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('PKN Orlen', 'Daniel Obajtek', 2020, 117, 5)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Acer', 'Jason Chen', 2019, 5, 5)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Honda', 'Takahiro Hachigo', 2019, 85, 8)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Fantom', 'Andre Cronje', 2021, 20, 8)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Epicor', 'Joseph L. Cowan', 2021, 5, 8)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Cognizant', 'Brian Humphries', 2021, 150, 6)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Aramco', 'Amin H. Nasser', 2020, 85, 6)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('EPOS', 'Karl-Heinz Fink', 2021, 10, 6)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Sofina', 'Harold Boël', 2020, 56, 9)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Lavazza', 'Alberto Lavazza', 2020, 50, 9)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Acronis', 'John Zanni', 2021, 35, 9)
