Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Philip Morris', 'André Calantzopoulos', '1973-05-15', 157.5 , 2)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Shell', 'Ben Van Beurden', '1996-03-04', 27, 2)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Ray Ban', 'Francesco Milleri', '2017-07-07', 10, 2)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Red Bull', 'Franz Watzlawick', '2005-03-06', 200, 1)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Aston Martin', 'Amedeo Felisa', '2018-02-20', 30, 1)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Honda', 'Takahiro Hachigo', '2019-03-25', 25, 1)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Petronas', 'Wan Zulkiflee Wan Ariffin', '2009-12-21', 125, 3)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Ineos', 'Sir James Arthur Ratcliffe', '2020-02-10', 35, 3)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('UBS', 'Ralph Hamers', '2010-03-23', 30, 3)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('BWT', 'Ralf Weber', '2022-03-12', 100, 4)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Castrol', 'Bernard Looney', '2022-03-13', 25, 4)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Microsoft', 'Satya Nadella', '1977-05-06', 30, 4)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Gulf', 'Michael K. Wirth', '1968-01-08', 145, 5)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Dell Technologies', 'Michael Dell', '2018-02-08', 50, 5)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Google', 'Sundar Pichai', '2022-03-19', 35, 5)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Haas', 'Gene Haas', '2016-03-18', 160, 8)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('MoneyGram', 'Alexander Holmes', '2022-10-20', 15, 8)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('IONOS', 'Achim Weiss', '2021-03-10', 15, 8)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Alfa Romeo', 'Jean-Philippe Imparato', '2018-03-09', 150, 6)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('PKN Orlen', 'Daniel Obajtek', '2020-01-03', 117, 6)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Acer', 'Jason Chen', '2019-12-15', 5, 6)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Honda', 'Takahiro Hachigo', '2019-03-15', 85, 9)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Fantom', 'Andre Cronje', '2021-05-20', 20, 9)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Epicor', 'Joseph L. Cowan', '2021-10-15', 5, 9)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Cognizant', 'Brian Humphries', '2021-01-07', 150, 7)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Aramco', 'Amin H. Nasser', '2020-03-10', 85, 7)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('EPOS', 'Karl-Heinz Fink', '2021-02-05', 10, 7)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Sofina', 'Harold Boël', '2020-01-06', 56, 10)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Lavazza', 'Alberto Lavazza', '2020-01-08', 50, 10)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Acronis', 'John Zanni', '2021-02-24', 35, 10)
