Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Sakhir', 5.4, 'Bahrain International Circuit', 'Bahrain')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Jeddah', 6.2, 'Jeddah Corniche Street Circuit', 'Saudi-Arabien')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Melbourne', 5.3, 'Melbourne Grand Prix Circuit', 'Australien')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Imola', 4.9, 'Autodromo Enzo e Dino Ferrari', 'Italien')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Miami', 5.4, 'Miami International Autodrome', 'USA')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Barcelona', 4.7, 'Circuit de Catalunya', 'Spanien')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Monte Carlo', 3.3, 'Circuit de Monaco', 'Monaco')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Baku', 6, 'Baku City Circuit', 'Aserbaidschan')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Montreal', 4.4, 'Circuit Gilles Villeneuve', 'Kanada')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Silverstone', 5.9, 'Silverstone Circuit', 'Grossbritannien')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Spielberg', 4.3, 'Red Bull Ring', 'Österreich')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Le Castellet', 5.8, 'Circuit Paul Ricard', 'Frankreich')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Budapest', 4.4, 'Hungaroring', 'Ungarn')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Spa-Francorchamps', 7.0, 'Circuit de Spa-Francorchamps', 'Belgien')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Zandvoort', 4.3, 'Circuit Zandvoort', 'Niederlande')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Monza', 5.8, 'Autodromo Nazionale Monza', 'Italien')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Singapore City', 5.1, 'Singapore Street Circuit', 'Singapur')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Suzuka', 5.8, 'Suzuka International Racing Course', 'Japan')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Austin', 5.5, 'Circuit of The Americas', 'USA')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Mexico City', 4.3, 'Autodromo Hermanos Rodriguez', 'Mexiko')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Sao Paulo', 4.3, 'Autodromo Jose Carlos Pace', 'Brasilien')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Abu Dhabi', 5.6, 'Yas Marina Circuit', 'Vereinigte Arabische Emirate')
