Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Philip Morris', 'André Calantzopoulos', '1973-05-15', 157.5 )
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Shell', 'Ben Van Beurden', '1996-03-04', 27)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Ray Ban', 'Francesco Milleri', '2017-07-07', 10)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Red Bull', 'Franz Watzlawick', '2005-03-06', 200)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Aston Martin', 'Amedeo Felisa', '2018-02-20', 30)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Honda', 'Takahiro Hachigo', '2019-03-25', 25)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Petronas', 'Wan Zulkiflee Wan Ariffin', '2009-12-21', 125)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Ineos', 'Sir James Arthur Ratcliffe', '2020-02-10', 35)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('UBS', 'Ralph Hamers', '2010-03-23', 30)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('BWT', 'Ralf Weber', '2022-03-12', 100)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Castrol', 'Bernard Looney', '2022-03-13', 25)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Microsoft', 'Satya Nadella', '1977-05-06', 30)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Gulf', 'Michael K. Wirth', '1968-01-08', 145)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Dell Technologies', 'Michael Dell', '2018-02-08', 50)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Google', 'Sundar Pichai', '2022-03-19', 35)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Haas', 'Gene Haas', '2016-03-18', 160)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('MoneyGram', 'Alexander Holmes', '2022-10-20', 15)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('IONOS', 'Achim Weiss', '2021-03-10', 15)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Alfa Romeo', 'Jean-Philippe Imparato', '2018-03-09', 150)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('PKN Orlen', 'Daniel Obajtek', '2020-01-03', 117)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Acer', 'Jason Chen', '2019-12-15', 5)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Honda', 'Takahiro Hachigo', '2019-03-15', 85)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Fantom', 'Andre Cronje', '2021-05-20', 20)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Epicor', 'Joseph L. Cowan', '2021-10-15', 5)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Cognizant', 'Brian Humphries', '2021-01-07', 150)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Aramco', 'Amin H. Nasser', '2020-03-10', 85)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('EPOS', 'Karl-Heinz Fink', '2021-02-05', 10)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Sofina', 'Harold Boël', '2020-01-06', 56)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Lavazza', 'Alberto Lavazza', '2020-01-08', 50)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition)
Values ('Acronis', 'John Zanni', '2021-02-24', 35)