DBCC CHECKIDENT (Teams, RESEED, 0)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Red Bull Racing', 445, 'Franz Watzlawick', 2005)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Ferrari', 463, 'Benedetto Vigna', 1950)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Mercedes', 484, 'Toto Wolff', 1954)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Alpine', 272, 'Luca de Meo', 1977)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('McLaren', 269, 'Zak Brown', 1966)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Alfa Romeo', 132, 'Ernst Joseph Walch', 1993)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Aston Martin', 188, 'Lawrence Stroll', 2018)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Haas F1 Team', 173, 'Gene Haas', 2016)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('AlphaTauri', 138, 'Franz Watzlawick', 2006)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Williams', 141, 'Darren Fultz', 1977)
