Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Mattia', 'Binotto', 3, '1969-11-03')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Laurent', 'Mekies', 2, '1977-04-28')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Jock', 'Clear', 1.5, '1963-09-12')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Christian', 'Horner', 5, '1973-11-16')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Jonathan', 'Wheatley', 3, '1967-05-07')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Pierre', 'Wache', 0.5, '1974-12-10')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Toto', 'Wolff', 6, '1972-01-12')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Ron', 'Meadows', 3, '1964-02-07')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Mike', 'Elliott', 2, '1974-06-04')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Otmar', 'Szafnauer', 4.5, '1964-08-13')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Davide', 'Brivio', 1.5, '1964-07-17')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Matt', 'Harman', 0.5, '1985-04-04')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Andreas', 'Seidl', 4, '1976-01-06')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Paul', 'James', 2, '1967-08-10')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('James', 'Key', 1.25, '1972-01-14')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Frederic', 'Vasseur', 3, '1968-05-28')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Beat', 'Zehnder', 2.5, '1966-01-09')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Jan', 'Monchaux', 1, '1978-06-04')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Mike', 'Krack', 1.5, '1972-03-18')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Andy', 'Stevenson', 2, '1967-09-20')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Dan', 'Fallows', 3, '1973-11-13')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Günther', 'Steiner', 5, '1965-04-07')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Peter', 'Crolla', 2, '1988-03-05')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Ayao', 'Komatsu', 1, '1976-01-28')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Franz', 'Tost', 3.75, '1956-01-20')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Marco', 'Perrone', 3, '1985-09-10')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Jody', 'Egginton', 1, '1974-01-28')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Jost', 'Capito', 4.75, '1958-09-29')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Sven', 'Smeets', 0.75, '1972-05-12')
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr)
Values ('Francois-Xavier', ' Demaison', 0.25, '1980-07-25')