Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Red Bull Racing', 445, 'Franz Watzlawick', '2005-03-06')
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Ferrari', 463, 'Benedetto Vigna', '1950-05-21')
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Mercedes', 484, 'Toto Wolff', '1954-07-04')
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Alpine', 272, 'Luca de Meo', '1977-06-16')
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('McLaren', 269, 'Zak Brown', '1966-05-22')
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Alfa Romeo', 132, 'Ernst Joseph Walch', '1993-03-14')
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Aston Martin', 188, 'Lawrence Stroll', '2018-08-26')
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Haas F1 Team', 173, 'Gene Haas', '2016-03-20')
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('AlphaTauri', 138, 'Franz Watzlawick', '2006-03-12')
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Williams', 141, 'Darren Fultz', '1977-05-08')