Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Mattia', 'Binotto', 3, '1969-11-03',0)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Laurent', 'Mekies', 2, '1977-04-28',1)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Jock', 'Clear', 1.5, '1963-09-12',2)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Christian', 'Horner', 5, '1973-11-16',3)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Jonathan', 'Wheatley', 3, '1967-05-07',4)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Pierre', 'Wache', 0.5, '1974-12-10',5)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Toto', 'Wolff', 6, '1972-01-12',6)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Ron', 'Meadows', 3, '1964-02-07',7)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Mike', 'Elliott', 2, '1974-06-04',8)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Otmar', 'Szafnauer', 4.5, '1964-08-13',9)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Davide', 'Brivio', 1.5, '1964-07-17',0)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Matt', 'Harman', 0.5, '1985-04-04',1)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Andreas', 'Seidl', 4, '1976-01-06',2)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Paul', 'James', 2, '1967-08-10',3)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('James', 'Key', 1.25, '1972-01-14',4)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Frederic', 'Vasseur', 3, '1968-05-28',5)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Beat', 'Zehnder', 2.5, '1966-01-09',6)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Jan', 'Monchaux', 1, '1978-06-04',7)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Mike', 'Krack', 1.5, '1972-03-18',8)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Andy', 'Stevenson', 2, '1967-09-20',9)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Dan', 'Fallows', 3, '1973-11-13',0)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Günther', 'Steiner', 5, '1965-04-07',1)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Peter', 'Crolla', 2, '1988-03-05',2)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Ayao', 'Komatsu', 1, '1976-01-28',3)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Franz', 'Tost', 3.75, '1956-01-20',4)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Marco', 'Perrone', 3, '1985-09-10',5)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Jody', 'Egginton', 1, '1974-01-28',6)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Jost', 'Capito', 4.75, '1958-09-29',7)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Sven', 'Smeets', 0.75, '1972-05-12',8)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsjahr,FK_TeamID)
Values ('Francois-Xavier', ' Demaison', 0.25, '1980-07-25',9)
