DBCC CHECKIDENT (Teams, RESEED, 0)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Red Bull Racing', 445, 'Franz Watzlawick', 2005)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Ferrari', 463, 'Benedetto Vigna', 1950)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Mercedes', 484, 'Toto Wolff', 1954)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Alpine', 272, 'Luca de Meo', 1977)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('McLaren', 269, 'Zak Brown', 1966)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Alfa Romeo', 132, 'Ernst Joseph Walch', 1993)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Aston Martin', 188, 'Lawrence Stroll', 2018)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Haas F1 Team', 173, 'Gene Haas', 2016)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('AlphaTauri', 138, 'Franz Watzlawick', 2006)
Insert into Teams (TeamName, Budget, Besitzer, Einstiegsjahr)
Values ('Williams', 141, 'Darren Fultz', 1977)
GO
DBCC CHECKIDENT (Mitarbeiter, RESEED, 0)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Mattia', 'Binotto', 3, '1969-11-03', 1)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Laurent', 'Mekies', 2, '1977-04-28', 1)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Jock', 'Clear', 1.5, '1963-09-12', 1)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Christian', 'Horner', 5, '1973-11-16', 0)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Jonathan', 'Wheatley', 3, '1967-05-07', 0)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Pierre', 'Wache', 0.5, '1974-12-10', 0)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Toto', 'Wolff', 6, '1972-01-12', 2)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Ron', 'Meadows', 3, '1964-02-07', 2)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Mike', 'Elliott', 2, '1974-06-04', 2)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Otmar', 'Szafnauer', 4.5, '1964-08-13', 3)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Davide', 'Brivio', 1.5, '1964-07-17', 3)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Matt', 'Harman', 0.5, '1985-04-04', 3)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Andreas', 'Seidl', 4, '1976-01-06', 4)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Paul', 'James', 2, '1967-08-10', 4)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('James', 'Key', 1.25, '1972-01-14', 4)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Frederic', 'Vasseur', 3, '1968-05-28', 5)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Beat', 'Zehnder', 2.5, '1966-01-09', 5)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Jan', 'Monchaux', 1, '1978-06-04', 5)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Mike', 'Krack', 1.5, '1972-03-18', 6)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Andy', 'Stevenson', 2, '1967-09-20', 6)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Dan', 'Fallows', 3, '1973-11-13', 6)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Günther', 'Steiner', 5, '1965-04-07', 7)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Peter', 'Crolla', 2, '1988-03-05', 7)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Ayao', 'Komatsu', 1, '1976-01-28', 7)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Franz', 'Tost', 3.75, '1956-01-20', 8)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Marco', 'Perrone', 3, '1985-09-10', 8)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Jody', 'Egginton', 1, '1974-01-28', 8)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Jost', 'Capito', 4.75, '1958-09-29', 9)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Sven', 'Smeets', 0.75, '1972-05-12', 9)
Insert into  Mitarbeiter (Vorname, Nachname, Einkommen, Geburtsdatum,FK_TeamID)
Values ('Francois-Xavier', ' Demaison', 0.25, '1980-07-25', 9)
GO
DBCC CHECKIDENT (Fahrer, RESEED, 0)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Max', 'Verstappen', 36000000, '1997-09-30', 1, 2011.5, 2015, 0)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Charles', 'Leclerc', 12000000, '1997-10-16', 16, 868, 2018, 1)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Sergio', 'Perez', 7000000, '1990-01-26', 11, 1201, 2011, 0)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('George', 'Russell', 4500000, '1998-02-15', 63, 294, 2019, 2)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Carlos', 'Sainz', 8000000, '1994-09-01', 55, 782.5, 2015, 1)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Lewis', 'Hamilton', 36000000, '1985-01-07', 44, 4405.5, 2007, 2)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Lando', 'Norris', 4500000, '1999-11-13', 4, 428, 2019, 4)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Esteban', 'Ocon', 4500000, '1996-09-17', 31, 364, 2016, 3)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Fernando', 'Alonso', 15000000, '1981-07-29', 14, 2061, 2001, 3)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Valtteri', 'Bottas', 8500000, '1989-08-28', 77, 1787, 2013, 5)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Daniel', 'Ricciardo', 15000000, '1989-07-01', 3, 1311, 2011, 4)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Sebastian', 'vettel', 15000000, '1987-07-03', 5, 3098, 2007, 6)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Kevin', 'Magnussen', 850000, '1992-10-05', 20, 183, 2014, 7)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Pierre', 'Gasly', 4500000, '1996-02-07', 10, 332, 2017, 8)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Lance', 'Stroll', 8000000, '1998-10-29', 18, 194, 2017, 6)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Mick', 'Schumacher', 850000, '1999-03-22', 47, 12, 2021, 7)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Yuki', 'Tsunoda', 500000, '2000-05-11', 22, 44, 2021, 8)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Guanyu', 'Zhou', 500000, '1999-05-30', 37, 6, 2022, 5)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Alexander', 'Albon', 1750000, '1996-03-23', 23, 201, 2019, 9)
Insert into Fahrer (Vorname, Nachname, Einkommen, Geburtsdatum, Startnummer, Punkte, Einstiegsjahr,FK_TeamId)
Values ('Nicholas', 'Latifi', 500000, '1995-06-29', 6, 9, 2020, 9)
GO
DBCC CHECKIDENT (Sponsoren, RESEED, 0)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Philip Morris', 'André Calantzopoulos', 1973, 157.5 , 1)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Shell', 'Ben Van Beurden', 1996, 27, 1)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Ray Ban', 'Francesco Milleri', 2017, 10, 1)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Red Bull', 'Franz Watzlawick', 2005, 200, 0)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Aston Martin', 'Amedeo Felisa', 2018, 30, 0)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Honda', 'Takahiro Hachigo', 2019, 25, 0)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Petronas', 'Wan Zulkiflee Wan Ariffin', 2009, 125, 2)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Ineos', 'Sir James Arthur Ratcliffe', 2020, 35, 2)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('UBS', 'Ralph Hamers', 2010, 30, 2)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('BWT', 'Ralf Weber', 2022, 100, 3)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Castrol', 'Bernard Looney', 2022, 25, 3)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Microsoft', 'Satya Nadella', 1977, 30, 3)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Gulf', 'Michael K. Wirth', 1968, 145, 4)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Dell Technologies', 'Michael Dell', 2018, 50, 4)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Google', 'Sundar Pichai', 2022, 35, 4)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Haas', 'Gene Haas', 2016, 160, 7)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('MoneyGram', 'Alexander Holmes', 2022, 15, 7)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('IONOS', 'Achim Weiss', 2021, 15, 7)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Alfa Romeo', 'Jean-Philippe Imparato', 2018, 150, 5)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('PKN Orlen', 'Daniel Obajtek', 2020, 117, 5)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Acer', 'Jason Chen', 2019, 5, 5)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Honda', 'Takahiro Hachigo', 2019, 85, 8)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Fantom', 'Andre Cronje', 2021, 20, 8)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Epicor', 'Joseph L. Cowan', 2021, 5, 8)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Cognizant', 'Brian Humphries', 2021, 150, 6)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Aramco', 'Amin H. Nasser', 2020, 85, 6)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('EPOS', 'Karl-Heinz Fink', 2021, 10, 6)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Sofina', 'Harold Boël', 2020, 56, 9)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Lavazza', 'Alberto Lavazza', 2020, 50, 9)
Insert into Sponsoren (Sponsorenname, Besitzer, Einstiegsjahr, Investition, FK_TeamId)
Values ('Acronis', 'John Zanni', 2021, 35, 9)
GO
DBCC CHECKIDENT (fährt, RESEED, 0)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-03-20', 0, 0)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-03-27', 1, 1)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-04-10', 2, 2)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-04-24', 3, 3)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-05-08', 4, 4)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-05-22', 5, 5)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-05-29', 6, 6)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-06-12', 7, 7)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-06-19', 8, 8)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-07-03', 9, 9)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-07-10', 10, 10)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-07-24', 11, 11)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-07-31', 12, 12)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-08-28', 13, 13)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-09-04', 14, 14)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-09-11', 15, 15)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-10-02', 16, 16)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-10-09', 17, 17)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-10-24', 18, 18)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-10-30', 19, 19)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-11-13', 20, 7)
Insert into fährt (Datum,FK_StreckenId,FK_FahrerId)
Values ('2022-11-20', 21, 4)
GO
DBCC CHECKIDENT (Rennstrecken, RESEED, 0)
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Sakhir', 5.4, 'Bahrain International Circuit', 'Bahrain')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Jeddah', 6.2, 'Jeddah Corniche Street Circuit', 'Saudi-Arabien')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Melbourne', 5.3, 'Melbourne Grand Prix Circuit', 'Australien')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Imola', 4.9, 'Autodromo Enzo e Dino Ferrari', 'Italien')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Miami', 5.4, 'Miami International Autodrome', 'USA')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Barcelona', 4.7, 'Circuit de Catalunya', 'Spanien')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Monte Carlo', 3.3, 'Circuit de Monaco', 'Monaco')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Baku', 6, 'Baku City Circuit', 'Aserbaidschan')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Montreal', 4.4, 'Circuit Gilles Villeneuve', 'Kanada')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Silverstone', 5.9, 'Silverstone Circuit', 'Grossbritannien')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Spielberg', 4.3, 'Red Bull Ring', 'Österreich')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Le Castellet', 5.8, 'Circuit Paul Ricard', 'Frankreich')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Budapest', 4.4, 'Hungaroring', 'Ungarn')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Spa-Francorchamps', 7.0, 'Circuit de Spa-Francorchamps', 'Belgien')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Zandvoort', 4.3, 'Circuit Zandvoort', 'Niederlande')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Monza', 5.8, 'Autodromo Nazionale Monza', 'Italien')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Singapore City', 5.1, 'Singapore Street Circuit', 'Singapur')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Suzuka', 5.8, 'Suzuka International Racing Course', 'Japan')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Austin', 5.5, 'Circuit of The Americas', 'USA')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Mexico City', 4.3, 'Autodromo Hermanos Rodriguez', 'Mexiko')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Sao Paulo', 4.3, 'Autodromo Jose Carlos Pace', 'Brasilien')
Insert into Rennstrecken (Ort, Streckenlänge, Streckenname, Land)
Values ('Abu Dhabi', 5.6, 'Yas Marina Circuit', 'Vereinigte Arabische Emirate')
GO